import Head from 'next/head'
import { useMemo, useState } from 'react'
import Image from 'next/image'

import magicCode from '../components/3x+1'

import styles from '../styles/Home.module.css'

export default function Home() {
	const [input, setInput] = useState()
	const [count, setCount] = useState()
	const [highest, setHighest] = useState()

	const onTextChange = (e) => {
		setInput(e.target.value)
		setHighest(0)
		setCount(0)
	}

	const inputIsNotANumber = useMemo(() => {
		return !!input && isNaN(input)
	}, [input])

	const onButtonClicked = () => {
		const response = magicCode(input)
		setCount(response[0])
		setHighest(response[1])
	}

	const onClear = () => {
		setInput(null)
		setCount(0)
		setHighest(0)
	}

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<h1 className={styles.title}>Hello friend!</h1>
			<p className={styles.description}>
				I'm assuming you're familiar with the 3x+1 problem (from Veritasium). I
				made this site so you could try it out
			</p>

			<input
				className={styles.input}
				value={input}
				onSubmit={onTextChange}
				onChange={onTextChange}
				placeholder='Enter a number here'
			/>
			{inputIsNotANumber ? (
				<p className={styles.errorText}>
					Dude, don't embarass me. Enter a number please!
				</p>
			) : (
				<p>
					<button className={styles.button} onClick={onButtonClicked}>
						Press me!
					</button>
				</p>
			)}

			{!!count && (
				<h2>
					The total number of loops was <bold>{count}</bold>
				</h2>
			)}

			{!!highest && (
				<h2>
					The highest number achieved was <bold>{highest}</bold>
				</h2>
			)}

			{!!count && (
				<button className={styles.secondaryButton} onClick={onClear}>
					clear
				</button>
			)}
		</div>
	)
}
